package ro.cub.btddigitalportals.entity;

public enum CategorieCerereRacordareEnum {
    INSTALATIE_RACORDARE_CONDUCTA_EXISTENTA,
    PRELUNGIRE_CONDUCTA_REALIZARE_INSTALATIE_RACORDARE,
    REALIZARE_INSTALATIE_NOUA_MONTARE_CONTOR_SEPARAT,
    MODIFICARE_TRASEU_SAU_INSTALATIE_EXISTENTA,
    MODIFICARE_DEBIT_INSTALATIE_EXISTENTA
}
